theme: jekyll-theme-cayman
plugins:
  - jekyll-sitemap
exclude:
  - doc/pytorch.md
  - doc/tensorflow_status.md
  - fwr13y/
  - test/d9m/README.md
  - test/d9m/might_do_menu.md
  - might_do_menu.md
  - pypi_description.md
  - pytorch.md
  - RELEASE.md
  - release_procedure.md
  - tensorflow_status.md
